### ISSUE TITLE
Can we use l2 weight decay with Lasagne?

### ISSUE THREAD

**Issue by erogol** [dnouri/nolearn#62]

**Comment by dnouri** [comment]
Yes, implement your own `lasagne.objectives.Objective` class that overrides method `get_loss` to add the regularization term.  Something like this should work (untested):

```python
    def get_loss(self, input=None, target=None, *args, **kwargs):
        network_output = self.input_layer.get_output(input, *args, **kwargs)
        if target is None:
            target = self.target_var

        reg = lasagne.regularization.l2(network_output)
        return self.loss_function(network_output, target) + reg * 0.0001
```

Then pass your class as the `objective` parameter into `NeuralNet`.

Feel free to reopen if this doesn't work.

**Comment by bobchennan** [comment]
```python
    class MyObjective(Objective):                                                                                                                                                                                                                 
       def get_loss(self, input=None, target=None, *args, **kwargs):                                                                                                                                                                              
            network_output = self.input_layer.get_output(input, *args, **kwargs)                                                                                                                                                                  
            if target is None:                                                                                                                                                                                                                    
                target = self.target_var                                                                                                                                                                                                          
                                                                                                                                                                                                                                              
            reg = lasagne.regularization.l2(network_output)                                                                                                                                                                                       
            return self.loss_function(network_output, target) + reg * 0.01         
```
Use the above code and it led to the following error:
```bash
      File "benchmark.py", line 165, in <module>
        net.fit(train,labels)
      File "/home/slhome/admin/cnx/local/lib/python2.7/site-packages/nolearn/lasagne.py", line 263, in fit
        self.initialize()
      File "/home/slhome/admin/cnx/local/lib/python2.7/site-packages/nolearn/lasagne.py", line 162, in initialize
        self.y_tensor_type,
      File "/home/slhome/admin/cnx/local/lib/python2.7/site-packages/nolearn/lasagne.py", line 218, in _create_iter_funcs
        loss_train = obj.get_loss(X_batch, y_batch)
      File "benchmark.py", line 114, in get_loss
        reg = lasagne.regularization.l2(network_output)
      File "/home/slhome/admin/cnx/src/lasagne/lasagne/regularization.py", line 10, in l2
        all_params = layers.get_all_non_bias_params(layer)
      File "/home/slhome/admin/cnx/src/lasagne/lasagne/layers/helper.py", line 218, in get_all_non_bias_params
        all_params = get_all_params(layer)
      File "/home/slhome/admin/cnx/src/lasagne/lasagne/layers/helper.py", line 154, in get_all_params
        params = sum([l.get_params() for l in layers], [])
    AttributeError: 'TensorVariable' object has no attribute 'get_params'
```

**Comment by dnouri** [comment]
Woops, try passing `self.input_layer` into `lasagne.regularization.l2` instead.

**Comment by bobchennan** [comment]
Finally solved this problem after reading code in Lasagne:
```python
class MyObjective(Objective):
    def get_loss(self, input=None, target=None, aggregation=None, **kwargs):
        """
        Get loss scalar expression

        :parameters:
            - input : (default `None`) an expression that results in the
                input data that is passed to the network
            - target : (default `None`) an expression that results in the
                desired output that the network is being trained to generate
                given the input
            - aggregation : None to use the value passed to the
                constructor or a value to override it
            - kwargs : additional keyword arguments passed to `input_layer`'s
                `get_output` method

        :returns:
            - output : loss expressions
        """
        network_output = self.input_layer.get_output(input, **kwargs)
        if target is None:
            target = self.target_var
        if aggregation not in self._valid_aggregation:
            raise ValueError('aggregation must be \'mean\', \'sum\', '
                             'or None, not {0}'.format(aggregation))
        if aggregation is None:
            aggregation = self.aggregation

        losses = self.loss_function(network_output, target)
        reg = lasagne.regularization.l2(self.input_layer)
        losses=losses+reg*0.01

        if aggregation is None or aggregation == 'mean':
            return losses.mean()
        elif aggregation == 'sum':
            return losses.sum()
        else:
            raise RuntimeError('This should have been caught earlier')
```

I'm not sure whether I use the right version of Lasagne. But it seems to work.

**Comment by dnouri** [comment]
@bobchennan Yours is right.  My code was based on an outdated version that didn't have the aggregation bit.

Though I guess it could be done with a little less writing by calling the base class method first.  What if you try this:

```python
class MyObjective(Objective):
    def get_loss(self, input=None, target=None, **kwargs):
        loss = super(MyObjective, self).get_loss(input=input, target=target, **kwargs)
        reg = lasagne.regularization.l2(self.input_layer)
        return loss + reg * 0.01
```

**Comment by bobchennan** [comment]
That's fine. I just copied the code from lasagne.

Now I use the following code:

class MyObjective(Objective):
    def get_loss(self, input=None, target=None, **kwargs):
        loss = super(MyObjective, self).get_loss(input=input,
target=target, deterministic=False, **kwargs)
        if not deterministic:
            return loss + 0.01 * lasagne.regularization.l2(self.input_layer)
        else:
            return loss

It gives the actual value of loss function on the cross-validation data.

2015-03-29 23:01 GMT+08:00 Daniel Nouri <notifications@github.com>:

**Comment by bobchennan** [comment]
That's fine. I just copied the code from lasagne.

Now I use the following code:
```python
class MyObjective(Objective):
    def get_loss(self, input=None, target=None, deterministic=False, **kwargs):
        loss = super(MyObjective, self).get_loss(input=input,
target=target, deterministic, **kwargs)
        if not deterministic:
            return loss + 0.01 * lasagne.regularization.l2(self.input_layer)
        else:
            return loss
```
It gives the actual value of loss function on the cross-validation data.

**Comment by dnouri** [comment]
Thanks for that.  This should be useful for folks wanting to do the same thing.  I noticed your line 4 has a syntax error though ("non-keyword arg after keyword arg"), and it should be:

```python
class MyObjective(Objective):
    def get_loss(self, input=None, target=None, deterministic=False, **kwargs):
        loss = super(MyObjective, self).get_loss(input=input,
target=target, deterministic=deterministic, **kwargs)
        if not deterministic:
            return loss + 0.01 * lasagne.regularization.l2(self.input_layer)
        else:
            return loss
```

Hopefully we finally nailed it.  :-)

Except a more sophisticated version might turn the magic `0.01` into a parameter of `__init__`.  An exercise for the reader...

**Comment by BrianMiner** [comment]
@dnouri may I ask what is probably a simple question? How does this function get used? Does something in nolearn need to also get adjusted? I tried to run nolearn / lasagne after simply running this function but it didnt seem to have any effect.

**Comment by BrianMiner** [comment]
Also curious, to which layer is this regularization applied?

**Comment by bobchennan** [comment]
@BrianMiner 
make sure that you use the lastest version of NoLearn/Lasagne.

Pass this class to the parameter 'Objective'

**Comment by BrianMiner** [comment]
Got it, thanks for this great library!

**Comment by valerioorfano** [comment]
@bobchennan, thanx  a lot. I am wondering how can i tune this regularisation function. I ve been working on 0.01 magic number. Is it the only param i can change? I ve tried multiple values but didn't get any benefit.

**Comment by bobchennan** [comment]
I think you can change the equation. For example, maybe you can set up
different value for different layers after carefully code reading.



2015-04-30 20:31 GMT+08:00 valerioorfano <notifications@github.com>:

**Comment by valerioorfano** [comment]
I' ve tried the following code:

class MyObjective(Objective):
    def __init__(self, mn = 0.01):
        self.magicnum = mn
    def get_loss(self, input=None, target=None, deterministic=False, **kwargs):
        loss = super(MyObjective, self).get_loss(input=input,target=target, deterministic=deterministic, **kwargs)
        if not deterministic:
            return loss + self.magicnum * lasagne.regularization.l2(self.input_layer)
        else:
            return loss


and then called NeuralNet with following parameter:

                 hidden1_objective = MyObjective(0.01),
                 hidden2_objective = MyObjective(0.1),
                 hidden3_objective = MyObjective(0.05)

I get the error:

TypeError: __init__() got an unexpected keyword argument 'objective'

**Comment by bobchennan** [comment]
instead of
```

hidden1_objective = MyObjective(0.01),
hidden2_objective = MyObjective(0.1),
hidden3_objective = MyObjective(0.05)


```
try
```
Objective=Myobjective
```
different weight can be specified in function get_loss

2015-04-30 21:23 GMT+08:00 valerioorfano <notifications@github.com>:

**Comment by valerioorfano** [comment]
Hi i m not sure i got you, sorry. How can i get different weights for layer?

Regards Valerio

Il giorno 30/apr/2015, alle ore 15:37, "cnx" <notifications@github.com> ha scritto:

**Comment by bobchennan** [comment]
Hack the code in lasagne.regularization.l2(self.input_layer),

classified these weights by their layer and multiply with different weights

2015-04-30 21:59 GMT+08:00 valerioorfano <notifications@github.com>:

**Comment by valerioorfano** [comment]
Hi and Thanx. I've used the belowe code, with different weight for each hidden layer, but still doesn't seem to give benefit.

def get_loss(self, input=None, target=None, deterministic=False, **kwargs):
        loss = super(MyObjective, self).get_loss(input=input,target=target, deterministic=deterministic, **kwargs)
        all_layers = get_all_layers(input_layers)
        hidden_layers = all_layers[1:-1]
        if not deterministic:
            for i,h_layer in enumerate(hiddenlayers):
                zeros = np.zeros(i).astype(int).astype(str)                
                denom = '10' +  ''.join(zeros) 
                loss = loss + i/float(denom) * lasagne.regularization.l2(h_layer)    
            return loss
        else:
            return loss

**Comment by dnouri** [comment]
Sorry, but we've had to update `objective` again.  See here for an example of using the new `objective` function to add losses together from multiple different network outputs: https://github.com/dnouri/nolearn/issues/105#issuecomment-121915528

And here for the default implementation of the new `objective`: https://github.com/dnouri/nolearn/pull/124#issue-95185140
